main/urls.py
from django.urls import path

from . import views

app_name = "app_vladislav_yurenya"

urlpatterns = [
    path(
        "",
        views.list_author_book,
        name="all_book_and_authors"),
    path(
        "create_book/",
        views.CreateBook.as_view(),
        name="create_book"),
    path(
        "detail_book/<int:pk>/",
        views.DetailBook.as_view(),
        name="detail_book"),
    path(
        "delete_book/<int:pk>/",
        views.DeleteBook.as_view(),
        name="delete_book"),
    path(
        "update_book/<int:pk>/",
        views.UpdateBook.as_view(),
        name="update_book"),
    path(
        "create_author/",
        views.CreateAuthor.as_view(),
        name="create_author"),
    path(
        "detail_author/<int:pk>/",
        views.DetailAuthor.as_view(),
        name="detail_author"),
    path(
        "delete_author/<int:pk>/",
        views.DeleteAuthor.as_view(),
        name="delete_author"),
    path(
        "update_author/<int:pk>/",
        views.UpdateAuthor.as_view(),
        name="update_author"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from project import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.core.validators import RegexValidator
from django.db import models


class Book(models.Model):
    title: models.CharField = models.CharField(
        max_length=30, verbose_name="Название книги"
    )
    genre: models.CharField = models.CharField(
        max_length=30, verbose_name="Жанр")
    author: models.ManyToManyField = models.ManyToManyField(
        "Author",
        verbose_name="Автор",
        through="BookAndAuthor",
        through_fields=("book", "author", "fio"),
    )
    year: models.IntegerField = models.IntegerField(verbose_name="Год издания")
    pages: models.IntegerField = models.IntegerField(
        verbose_name="Количество страниц")
    photo: models.ImageField = models.ImageField(
        verbose_name="Фотография книги", upload_to="all_photos/%Y/%m/%d/"
    )

    def save(self, *args, **kwargs) -> None:
        self.title, self.genre = self.title.capitalize(), self.genre.capitalize()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.title},{self.genre},{self.author},{self.year},{self.pages},{self.photo}"


class Author(models.Model):
    surname: models.CharField = models.CharField(
        max_length=30, verbose_name="Фамилия")
    name: models.CharField = models.CharField(
        max_length=30, verbose_name="Имя")
    patronymic: models.CharField = models.CharField(
        max_length=30, verbose_name="Отчество"
    )
    birthday = models.CharField(
        max_length=10,
        validators=[
            RegexValidator(
                r"^\d{2}\.\d{2}\.\d{4}$",
                "Дата должна быть в формате dd.mm.yyyy")],
        verbose_name="День рождения",
    )
    fio: models.CharField = models.CharField(max_length=30)

    def save(self, *args, **kwargs) -> None:
        self.surname, self.name, self.patronymic = (
            self.surname.capitalize(),
            self.name.capitalize(),
            self.patronymic.capitalize(),
        )
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.fio}"


class BookAndAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    fio = models.CharField(max_length=30)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.author:
            self.fio = f"{self.author.fio}"

    def __str__(self) -> str:
        return f"{self.book},{self.author},{self.fio}"

main/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)

from .models import Book, Author, BookAndAuthor


class CreateBook(CreateView):
    model = Book
    template_name = "main/create_book.html"
    success_url = reverse_lazy("app_vladislav_yurenya:all_book_and_authors")
    fields = [
        "title",
        "photo",
        "year",
        "genre",
        "pages",
        "author",
    ]

    def form_valid(self, form):
        new = form.save(commit=False)
        form.cleaned_data["name_author"] = Author.objects.order_by("fio")
        return super().form_valid(form)


class ListBook(ListView):
    model = Book
    template_name = "main/all_book.html"


class DetailBook(DetailView):
    model = Book
    template_name = "main/detail_book.html"


class DeleteBook(DeleteView):
    model = Book
    template_name = "main/delete_book.html"
    success_url = reverse_lazy("app_vladislav_yurenya:all_book_and_authors")


class UpdateBook(UpdateView):
    model = Book
    template_name = "main/update_book.html"
    success_url = reverse_lazy("app_vladislav_yurenya:all_book_and_authors")
    fields = [
        "title",
        "photo",
        "year",
        "genre",
        "pages",
        "author",
    ]


class CreateAuthor(CreateView):
    model = Author
    template_name = "main/create_author.html"
    success_url = reverse_lazy("app_vladislav_yurenya:all_book_and_authors")
    fields = [
        "surname",
        "name",
        "patronymic",
        "birthday",
    ]

    def form_valid(self, form):
        new = form.save(commit=False)
        x = f"{new.surname.capitalize()} {new.name[0].upper()}{'.'}{new.patronymic[0].upper()}{'.'}"
        new.fio = x
        new.save()
        return super().form_valid(form)


class ListAuthor(ListView):
    model = Author
    template_name = "main/all_author.html"


class DetailAuthor(DetailView):
    model = Author
    template_name = "main/detail_author.html"


class DeleteAuthor(DeleteView):
    model = Author
    template_name = "main/delete_author.html"
    success_url = reverse_lazy("app_vladislav_yurenya:all_book_and_authors")


class UpdateAuthor(UpdateView):
    model = Author
    template_name = "main/update_author.html"
    success_url = reverse_lazy("app_vladislav_yurenya:all_book_and_authors")
    fields = [
        "name",
        "surname",
        "patronymic",
        "birthday",
    ]


def list_author_book(request):
    author = Author.objects.all()
    book = Book.objects.all()
    return render(request, "main/all_book.html",
                  {"author": author, "book": book})

main/templates/main/all_book.html
{% extends 'main/base.html' %}
{% block content %}
<h1>Все книги и авторы</h1>
<a href="{% url 'app_vladislav_yurenya:create_book' %}">
<button class = 'glow-on-hover' type="submit" >Добавить книгу</button>
</a>
<a href="{% url 'app_vladislav_yurenya:create_author' %}">
<button class = 'glow-on-hover' type="submit" >Создать автора</button>
</a>
<h1>Список авторов:</h1>
  <ul>
  {% for i in author %}
    <h1>{{ i.fio }}</h1>
    <a href="{%url 'app_vladislav_yurenya:detail_author' i.pk%}" >
      <button class="glow-on-hover" type="sumbit">Подробнее</button>
    </a>
<hr>
    {% endfor %}
      </ul>
<h1>Книги:</h1>
  <ul>

  {% for i in book %}
    <h1>{{ i.title }}</h1>
    <p><img class="img-articale-left thumb" src = "{{ i.photo.url }}" width="160px"></p>
    {% for author in i.author.all %}
    <p>Автор: {{ author.fio }}</p>
    {% endfor %}
    <a href="{%url 'app_vladislav_yurenya:detail_book' i.pk%}" >
      <button class="glow-on-hover" type="sumbit">Подробнее</button>
    </a>

{% endfor %}

    </ul>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>VARFALOMEY</title>
    <link type='text/css' href="{% static 'main/css/button.css' %}" rel="stylesheet" >
    <link type='text/css' href="{% static 'main/css/styles.css' %}" rel="stylesheet" >

 <link rel="shortcut icon" href="{% static 'main/images/main.ico' %}" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

</head>
<body>

<div class="ocean">
  <div class="wave"></div>
  <div class="wave"></div>
</div>
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/create_author.html
{% extends 'main/base.html' %}
{% block content %}
<h1>Добавление автора</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="glow-on-hover" type="submit">Добавить</button>
</form><br>
<a href="{%url 'app_vladislav_yurenya:all_book_and_authors' %}" >
      <button class="glow-on-hover" type="sumbit">Отмена</button>
    </a>

{% endblock %}

main/templates/main/create_book.html
{% extends 'main/base.html' %}
{% block content %}
<h1>Добавление книги</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="glow-on-hover" type="submit">Опубликовать</button>
</form><br>
<a href="{%url 'app_vladislav_yurenya:all_book_and_authors' %}" >
      <button class="glow-on-hover" type="sumbit">Отмена</button>
    </a>

{% endblock %}

main/templates/main/delete_author.html
{% extends 'main/base.html' %}
{% block content %}
<h1>Удалить автора?!</h1>
<form method="POST">
    {% csrf_token %}
      <button class="glow-on-hover" type="sumbit">В Вальгаллу</button>
</form><br>
<a href="{%url 'app_vladislav_yurenya:detail_author' object.pk %}" >
      <button class="glow-on-hover" type="sumbit">Пощады</button>
    </a>
{% endblock %}

main/templates/main/delete_book.html
{% extends 'main/base.html' %}
{% block content %}
<h1>Действительно удалить?</h1>
<form method="POST">
    {% csrf_token %}
      <button class="glow-on-hover" type="sumbit">Да</button>
</form><br>
<a href="{%url 'app_vladislav_yurenya:detail_book' object.pk %}" >
      <button class="glow-on-hover" type="sumbit">Нет</button>
    </a>
{% endblock %}

main/templates/main/detail_author.html
{% extends 'main/base.html' %}
{% block content %}
<ul>
   <h1>Фамилия: {{ object.surname }}</h1>
    <p>Имя: {{ object.name }}</p>
    <p>Отчество: {{ object.patronymic }}</p>
    <p>День рождения: {{ object.birthday }}</p>
    <a href="{%url 'app_vladislav_yurenya:update_author' object.pk%}" >
      <button class="glow-on-hover" type="sumbit">Редактировать</button>
    </a><br><br>
 <a href="{%url 'app_vladislav_yurenya:delete_author' object.pk%}" >
      <button class="glow-on-hover" type="sumbit">Удалить</button>
    </a><br><br>
    <a href="{%url 'app_vladislav_yurenya:all_book_and_authors' %}" >
      <button class="glow-on-hover" type="sumbit">Назад</button>
    </a>
</ul>
{% endblock %}

main/templates/main/detail_book.html
{% extends 'main/base.html' %}
{% block content %}
<ul>
   <h1>{{ object.title }}</h1>
    <p><img class="img-articale-left thumb" src = "{{ object.photo.url }}" width="160px"> </p>
    <p>Год издания: {{ object.year }}</p>
    <p>Жанр: {{ object.genre }}</p>
    <p>Количество страниц: {{ object.pages }}</p>
    {% for author in object.author.all %}
<p>Автор: {{ author.fio }}</p>
{% endfor %}
    <a href="{%url 'app_vladislav_yurenya:update_book' object.pk%}" >
      <button class="glow-on-hover" type="sumbit">Изменить</button>
    </a><br><br>
 <a href="{%url 'app_vladislav_yurenya:delete_book' object.pk%}" >
      <button class="glow-on-hover" type="sumbit">Удалить</button>
    </a><br><br>
    <a href="{%url 'app_vladislav_yurenya:all_book_and_authors' %}" >
      <button class="glow-on-hover" type="sumbit">Назад</button>
    </a>
</ul>
{% endblock %}

main/templates/main/update_author.html
{%extends 'main/base.html'%}
{%block content%}
<h1>Редактирование книги</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
      <button class="glow-on-hover" type="submit">Сохранить</button>
</form><br>
<a href="{%url 'app_vladislav_yurenya:detail_author' object.pk%}" >
      <button class="glow-on-hover" type="sumbit">Отмена</button>
    </a>
{%endblock%}

main/templates/main/update_book.html
{%extends 'main/base.html'%}
{%block content%}
<h1>Редактирование книги</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
      <button class="glow-on-hover" type="submit">Сохранить</button>
</form><br>
<a href="{%url 'app_vladislav_yurenya:detail_book' object.pk%}" >
      <button class="glow-on-hover" type="sumbit">Отмена</button>
    </a>
{%endblock%}